### ISSUE TITLE
Significant Response Delay After Idle Period in Version 3

### ISSUE THREAD

**Issue by askhat-spec** [aiogram/aiogram#1500] opened 2024-05-31 07:21 UTC
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Oracle Linux 7

### Python version

3.9

### aiogram version

3.6.0

### Expected behavior

The bot should respond promptly without significant delay, even after being idle.

### Current behavior

The bot responds with a significant delay after being idle for more than 15 seconds.
![echo_bot](https://github.com/aiogram/aiogram/assets/59597538/a95bfa54-e8be-48dc-befc-9c1518ac6fb0)

### Steps to reproduce

Deploy a standard bot on a server.
Allow the bot to be idle for more than 15 seconds.
Send a message to the bot.
Observe the delay in the bot's response.

### Code example

```python3
import os
import sys
import asyncio
import logging

from aiogram import Bot, types
from aiogram import Dispatcher
from aiogram.client.default import DefaultBotProperties
from aiogram.enums import ParseMode

TOKEN = os.getenv('TOKEN')

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s [%(name)s] - %(message)s",
    stream=sys.stdout,
    force=True,
)
logger = logging.getLogger(__name__)

dp = Dispatcher()

@dp.message()
async def echo(message: types.Message):
    logger.info('Handler Start')
    await message.answer(message.text)
    logger.info('Handler End')


async def main():
    bot = Bot(
        token=TOKEN, 
        default=DefaultBotProperties(parse_mode=ParseMode.HTML)
    )
    await dp.start_polling(bot, skip_updates=True)


if __name__ == '__main__':
    try:
        logger.info("Starting bot")
        asyncio.run(main())
    except (KeyboardInterrupt, SystemExit):
        logger.info("Bot stopped!")
```

### Additional information

This issue is not present in version 2.x.

**Comment by Vadim-Khristenko** [comment] 2024-06-01 18:46
Hello!

Can you tell if these messages were sent when the bot was stopped or when it was running?
And is this repeated in AIogram 3.7.0?

If the bot processed the messages that were sent to it when it was stopped, then as I remember it calculates the time from the moment the user sent the message until the moment it was processed by the handler.

**Comment by JrooTJunior** [comment] 2024-06-02 20:04
> as I remember it calculates the time from the moment the user sent the message until the moment it was processed by the handler.

is not correct: https://github.com/aiogram/aiogram/blob/0335bb14fcacdd07d271709b783dca105952719b/aiogram/dispatcher/dispatcher.py#L145-L178

The log message indicates the total duration of the event processing process.

**Comment by JrooTJunior** [comment] 2024-06-02 20:08
This issue is not reproducible.
Looks like trouble is on your side (network or machine).

You should trace your application and understand what actually is going on.
Check ping, traceroute, IPv6 configuration, enable tracing in your application, enable outgoing reuqests middleware to measure request duration.

**Comment by askhat-spec** [comment] 2024-06-02 21:16
Hello! I have tested this on different computers, so to reproduce this issue, please make sure you follow all the steps correctly as I described. After sending several messages, wait more than 15-20 seconds before sending the next message. The delay occurs exactly at the moment when message.answer() is called. Here is a screenshot from my work laptop, where the delay isn't as significant, but it is still present:

![test](https://github.com/aiogram/aiogram/assets/59597538/c6ae85a2-87e5-4212-86e2-888dcd1a2ff7)

**Comment by askhat-spec** [comment] 2024-06-02 21:40
> Can you tell if these messages were sent when the bot was stopped or when it was running? And is this repeated in Aiogram 3.7.0?

Yes, this issue is present in this version as well. However, in the second version, this problem does not occur. Here is a screenshot:

![test_botV2](https://github.com/aiogram/aiogram/assets/59597538/154f7f13-2199-4d7c-9b09-29bbb0e240a5)


> **Addition: I could not reproduce this bug, so I’m clarifying the details.**

Please make sure everything is done correctly. After sending several messages, wait 15-20 seconds and only then send another message. Compare the processing time with others.

**Comment by JrooTJunior** [comment] 2024-06-06 23:05
Still not reproducible from your code example.
![image](https://github.com/aiogram/aiogram/assets/6726423/b241e3af-6683-4ba1-b135-982a100f9636)

**Comment by Olegt0rr** [comment] 2024-06-07 07:39
I have more significant response on first request (4s).
Your issue also reproduced, but with less time (highlighted)

![telegram-cloud-photo-size-2-5411385719395571675-y](https://github.com/aiogram/aiogram/assets/25399456/7cce8a06-5d20-4b60-8ea4-22caacb31cd8)

**Comment by JrooTJunior** [comment] 2024-06-07 15:50
I succeeded in reproducing the problem, I am investigating the reasons.

**Comment by JrooTJunior** [comment] 2024-06-16 23:28
The short answer for this issue - synchronous DNS resolver sucks.

More detailed explanation:
`aiohttp` by default has an DSN cache for 10 seconds, so the slow response happens after more than 10 seconds.
Previously aiohttp uses `aiodns` for speedup DNS resolving but in due to this library doesn't support all required functionality for aiohttp it is disabled few releases ago (details: https://github.com/aio-libs/aiohttp/issues/2254).

There's only one simple solution I can see at the moment - I'll try to increase the DSN cache timeout to about an hour in the next release to reduce the frequency of slow requests.
Alternative way is to enable `aiodns` for `aiogram` client session but it can be incompatible with some of bots that is already implemented and developer trying to update aiogrm version in due to aiohttp AsyncResolver should be created inside coroutine but bot with client session can be created outside of the any coroutine.

**Closed** 2024-06-16 23:51 UTC
Labels: bug, confirmed

**Comment by JrooTJunior** [comment] 2024-07-24 15:30
@askhat-spec, please update aiohttp to the last version and try again. 3 days ago already updated: https://github.com/aio-libs/aiohttp/pull/8522

**Comment by askhat-spec** [comment] 2024-07-25 07:43
Thank you for the recommendation. I'm glad they are bringing back AsyncResolver. As far as I can see, they have only included it in the beta version for now. I will definitely update as soon as it is added to the new version.

**Comment by askhat-spec** [comment] 2024-07-31 04:15
@JrooTJunior can't upgrage aiohttp to 3.10

`aiogram 3.10.0 requires aiohttp~=3.9.0`
