### ISSUE TITLE
Wrong permissions

### ISSUE THREAD

**Issue by LenaTDDS** [aiogram/aiogram#1138] opened 2023-03-09 15:25 UTC
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Python Version: 3.10.6
* aiogram version: 3.0.0b7
* aiohttp version: 3.8.4
* uvloop version (if installed): -

## Current Behavior

When I get information about a participant via get_chat_member, and at the same time this participant is the creator of the chat, then his rights are None, instead of bool

## Expected Behavior

When I get information about a participant via get_chat_member, and at the same time this participant is the creator of the chat, then his rights are bool, instead of None

## Failure Information (for bugs)

No failure information

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Get information with code like `await bot.get_chat_member(message.chat.id, message.reply_to_message.from_user.id)`
2. Parse it

### Failure Logs

`can_be_edited=None can_manage_chat=None can_delete_messages=None can_manage_video_chats=None`, etc...

**Comment by JrooTJunior** [comment] 2023-03-11 18:24
Is not a bug.

Look at Bot API documentation for ChatMemberOwner entity: https://core.telegram.org/bots/api#chatmemberowner
This object has no such attributes, so it can't be represented in this object.

You should check object type before interact with their attributes.

I'm closing this issue, feel free to re-open it or create new-one if you have any additional questions.

**Closed by JrooTJunior** 2023-03-11 18:24 UTC
