### ISSUE TITLE
Chat.update_chat() fails for private chats obtained from Bot.get_chat()

### ISSUE THREAD

**Issue by jonowo** [aiogram/aiogram#513] opened 2021-02-22 17:03 UTC
## Context
* Operating System: Windows 10
* Python Version: 3.9.0
* aiogram version: 2.11.2
* aiohttp version: 3.7.3
* uvloop version (if installed): N/A

## Expected Behavior
`Chat` is updated successfully.

## Current Behavior
A `TypeError` is raised.

### Steps to Reproduce

1. Run the following code
```python
import logging

from aiogram import Bot, Dispatcher, executor, types

logging.basicConfig(level=logging.INFO)
bot = Bot(token="TOKEN HERE")
dp = Dispatcher(bot)


@dp.message_handler(commands="test")
async def test(message: types.Message) -> None:
    # No error if the following line is replaced with chat = message.chat
    chat = await bot.get_chat(message.chat.id)
    await chat.update_chat()  # Error in this function call


if __name__ == "__main__":
    executor.start_polling(dp, skip_updates=True)

```
2. Send `/test` to the bot in its DMs or a private supergroup.

### Failure Logs
```
Traceback (most recent call last):
  File "C:\Users\jono\AppData\Roaming\Python\Python39\site-packages\aiogram\dispatcher\dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\jono\AppData\Roaming\Python\Python39\site-packages\aiogram\dispatcher\dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\jono\AppData\Roaming\Python\Python39\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\jono\AppData\Roaming\Python\Python39\site-packages\aiogram\dispatcher\dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\jono\AppData\Roaming\Python\Python39\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\test\aiogramtest.py", line 14, in test
    await chat.update_chat()
  File "C:\Users\jono\AppData\Roaming\Python\Python39\site-packages\aiogram\types\chat.py", line 123, in update_chat
    self[key] = value
  File "C:\Users\jono\AppData\Roaming\Python\Python39\site-packages\aiogram\types\base.py", line 226, in __setitem__
    return self.props[key].set_value(self, value, self.conf.get('parent', None))
  File "C:\Users\jono\AppData\Roaming\Python\Python39\site-packages\aiogram\types\fields.py", line 57, in set_value
    value = self.deserialize(value, parent)
  File "C:\Users\jono\AppData\Roaming\Python\Python39\site-packages\aiogram\types\fields.py", line 114, in deserialize
    parent = weakref.ref(parent)
TypeError: cannot create weak reference to 'NoneType' object
```

**Comment by darksidecat** [comment] 2021-03-27 22:06
did dome investigation:
```
print(message.chat.values) ↴
{'id': хххххххх, 'first_name': 'ххх', 'last_name': 'ххх', 'type': 'private'}

chat = await bot.get_chat(message.chat.id)
print(chat.values) ↴
{'id': хххххххх, 'first_name': 'ххх', 'last_name': 'ххх', 'type': 'private', 'photo': <aiogram.types.chat_photo.ChatPhoto object at 0x00000235408C2EE0>}
```
difference is in photo value that can`t be deserialize properly, as far as I understand

also here some detailed logs
```
  File "C:/Users/Darksidecat/PycharmProjects/aiogram-tests\main.py", line 21, in test
    await chat2.update_chat()  # Error in this function call
          │     └ <function Chat.update_chat at 0x0000021E92F7B9D0>
          └ <aiogram.types.chat.Chat object at 0x0000021E931B5C40>
  File "C:\Users\Darksidecat\anaconda3\envs\aiogram-tests\lib\site-packages\aiogram\types\chat.py", line 125, in update_chat
    self[key] = value
    │    │      └ {'small_file_id': 'AQADAgADq6cxG0bcJhIACLqdo5YuAAMCAANG3CYSAASQcbFK5jlIMuprAAIeBA', 'small_file_unique_id': 'AQADup2jli4AA-pr...
    │    └ 'photo'
    └ <aiogram.types.chat.Chat object at 0x0000021E931B5C40>
  File "C:\Users\Darksidecat\anaconda3\envs\aiogram-tests\lib\site-packages\aiogram\types\base.py", line 230, in __setitem__
    return self.props[key].set_value(self, value, self.conf.get('parent', None))
           │    │     │              │     │      │    └ <property object at 0x0000021E92CC2C20>
           │    │     │              │     │      └ <aiogram.types.chat.Chat object at 0x0000021E931B5C40>
           │    │     │              │     └ {'small_file_id': 'AQADAgADq6cxG0bcJhIACLqdo5YuAAMCAANG3CYSAASQcbFK5jlIMuprAAIeBA', 'small_file_unique_id': 'AQADup2jli4AA-pr...
           │    │     │              └ <aiogram.types.chat.Chat object at 0x0000021E931B5C40>
           │    │     └ 'photo'
           │    └ <property object at 0x0000021E92CC2C70>
           └ <aiogram.types.chat.Chat object at 0x0000021E931B5C40>
  File "C:\Users\Darksidecat\anaconda3\envs\aiogram-tests\lib\site-packages\aiogram\types\fields.py", line 57, in set_value
    value = self.deserialize(value, parent)
            │    │           │      └ None
            │    │           └ {'small_file_id': 'AQADAgADq6cxG0bcJhIACLqdo5YuAAMCAANG3CYSAASQcbFK5jlIMuprAAIeBA', 'small_file_unique_id': 'AQADup2jli4AA-pr...
            │    └ <function Field.deserialize at 0x0000021E92CC5820>
            └ <aiogram.types.fields.Field object at 0x0000021E92F77AF0>
  File "C:\Users\Darksidecat\anaconda3\envs\aiogram-tests\lib\site-packages\aiogram\types\fields.py", line 114, in deserialize
    parent = weakref.ref(parent)
             │       │   └ None
             │       └ <class 'weakref'>
             └ <module 'weakref' from 'C:\\Users\\Darksidecat\\anaconda3\\envs\\aiogram-tests\\lib\\weakref.py'>
```

Unfortunately, I can’t help you anymore due to lack of knowledge.

**Comment by darksidecat** [comment] 2021-04-09 11:06
Maybe change default value to `self` in this code will fix this?

https://github.com/aiogram/aiogram/blob/79c59b34f9141427d221842662dcef2eb90a558f/aiogram/types/base.py#L230

```return self.props[key].set_value(self, value, self.conf.get('parent', self))```

It works. But so far it is difficult for me to figure out whether this is the correct solution to the problem or not.

**Comment by darksidecat** [comment] 2021-04-28 07:32
> Maybe change default value from `None` to `self` in this code will fix this?

@JrooTJunior Should I look further for the cause of the bug? Or that can be the solution?

**Comment by ShiroNoHaga** [comment] 2022-01-05 08:53
Have the same problem. Any solutions yet?

**Comment by Olegt0rr** [comment] 2022-01-10 08:43
@ShiroNoHaga,
please wait for #806 PR become merged or use workaround:
```python
async def handler(message: Message):
    bot = message.bot
    chat = message.chat
    full_chat = await bot.get_chat(chat.id)
```

**Closed** 2022-02-08 00:30 UTC
Labels: bug, confirmed
