### ISSUE TITLE
Polling doesn't stop on receiving SIGTERM in Docker

### ISSUE THREAD

**Issue by drdilyor** [aiogram/aiogram#591] opened 2021-05-24 23:20 UTC
I have been using docker for a while and I have noticed 10 second delay before stopping the container. Now I realized that it is because aiogram doesn't shutdown when SIGTERM signal was sent. When do `docker kill --signal SIGINT`, everything looks normal now.

Is it possible to make aiogram to shutdown on SIGTERM as well?

**Comment by drdilyor** [comment] 2021-05-24 23:36
[Also I use JSON syntax for CMD in my Dockerfile](https://docs.docker.com/compose/faq/#why-do-my-services-take-10-seconds-to-recreate-or-stop)

**Comment by evgfilim1** [comment] 2021-05-25 06:35
Hello, @drdilyor. I see you didn't follow any issue template, so can you provide us a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by drdilyor** [comment] 2021-05-26 15:27
[Video](https://github.com/drdilyor/drdilyor.github.io/blob/master/simplescreenrecorder-2021-05-26_19.08.05.mkv?raw=true)
[Dockerfile](https://pastebin.com/cUAPjBQi)
[mre.py](https://pastebin.com/us4zrJqz)

**Comment by drdilyor** [comment] 2021-05-26 15:31
Also it works normally when I add [these lines of code](https://github.com/drdilyor/aiogram/blob/1389b4de9c6e93cd7af7ed72f727afb2d1c38a38/aiogram/utils/executor.py#L20)

**Comment by evgfilim1** [comment] 2021-05-30 06:12
Btw this issue happens only in docker :thinking: 

https://asciinema.org/a/tLyPYlfnexaL9bFrI7HPw0wjh

**Comment by kamikazebr** [comment] 2021-06-20 02:41
> [Video](https://github.com/drdilyor/drdilyor.github.io/blob/master/simplescreenrecorder-2021-05-26_19.08.05.mkv?raw=true)
> [Dockerfile](https://pastebin.com/cUAPjBQi)
> [mre.py](https://pastebin.com/us4zrJqz)

You're exposing your bot token, it's okay?

**Comment by drdilyor** [comment] 2021-06-25 12:49
@kamikazebr yes, I have already deleted the bot after 2days

**Comment by MasterGroosha** [comment] 2021-07-10 07:25
Possibly related: https://github.com/aio-libs/aiohttp/pull/1946

**Comment by evgfilim1** [comment] 2021-07-10 07:31
> Possibly related: [aio-libs/aiohttp#1946](https://github.com/aio-libs/aiohttp/pull/1946)

@MasterGroosha not really as that pull is about aiohttp web server but this issue is about polling

**Comment by mmkhitaryan** [comment] 2021-07-24 08:09
@drdilyor 
Looks like the problem is that you are using CMD instead of ENTRYPOINT as [described here](https://stackoverflow.com/a/64960372/7415288).

**Comment by evgfilim1** [comment] 2021-07-24 08:46
> @drdilyor
> Looks like the problem is that you are using CMD instead of ENTRYPOINT as [described here](https://stackoverflow.com/a/64960372/7415288).

@mmkhitaryan, I've just checked, changing `CMD` to `ENTRYPOINT` won't help :(

**Comment by drdilyor** [comment] 2021-07-24 17:19
I assume that this issue more generally belongs to python, i've written a simple script and it also hangs on SIGTERM.... Alas, I'm a junior yet. Sorry for that:(

**Comment by JrooTJunior** [comment] 2023-08-04 18:13
Fixed in v3

**Closed** 2023-08-04 18:22 UTC
Labels: bug, help wanted, confirmed, 2.x
