### ISSUE TITLE
send_chat_action fails

### ISSUE THREAD

**Issue by kamikaze** [aiogram/aiogram#188] opened 2019-08-14 15:07 UTC
```python
@dp.message_handler()
async def echo(message: types.Message):
    await bot.send_chat_action(message.chat.id, 'typing')
    await bot.send_message(message.chat.id, message.text)
```

Fails with:

```
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiogram/dispatcher/dispatcher.py", line 255, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiogram/bot/bot.py", line 93, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiogram/bot/base.py", line 184, in request
    proxy=self.proxy, proxy_auth=self.proxy_auth, timeout=self.timeout, **kwargs)
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiogram/bot/api.py", line 97, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 905, in create_connection
    type=socket.SOCK_STREAM, proto=proto, flags=flags, loop=self)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1275, in _ensure_resolved
    proto=proto, flags=flags)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
TypeError: getaddrinfo() argument 1 must be string or None
```

If I comment out any of awaits - no failures happen

**Comment by Birdi7** [comment] 2019-08-14 22:49
I've run [this](https://gist.github.com/Birdi7/5dbae1619dc3908a4b4218bd587305d1) listing which is basically is your code and it didn't raise me any exceptions. I use the latest version of the aiogram and the aiohttp. Could you provide more info on reproducing this issue? I am not sure if it connects with the aiogram itself, looks like the problem is in some network library

**Comment by JrooTJunior** [comment] 2019-08-15 13:59
Won't fix.
This bug can't be reproduced in other environments.

Maybe you can attach more detailed example of code where this problem can be reproduced?

**Closed** 2019-09-04 11:19 UTC
Labels: wontfix

**Comment by ches993** [comment] 2021-02-07 13:21
kamikaze are you have success for solve your problem?
Because i have exactly too problem

**Comment by Olegt0rr** [comment] 2021-02-10 21:39
> kamikaze are you have success for solve your problem?
> Because i have exactly too problem

Please run `pip freeze` and port the result here

**Comment by ches993** [comment] 2021-02-15 15:43
Thanks for the answer, but I have already solved this problem.
ср, 10 февр. 2021 г. в 23:50, Oleg A. <notifications@github.com>:

**Comment by evgfilim1** [comment] 2021-02-16 10:39
> already solved this problem

Can you share the solution with us in case of someone else will encounter the same failure?

**Comment by ches993** [comment] 2021-02-17 18:41
Here you can see the code and failure.
I used :
Anaconda (version 1.7.2)
Python (version 3.8.5)
Spyder (version 4.2)
In my case as i understood the problem was not code but in the Spyder
(version 4.2)
The solution was to switch to Visual studio.
Perhaps it was not what you were looking for.

вт, 16 февр. 2021 г. в 12:40, evgfilim1 <notifications@github.com>:

**Comment by ches993** [comment] 2021-02-17 18:48
https://ru.stackoverflow.com/questions/1241208/%d0%9f%d1%80%d0%b8-%d0%b7%d0%b0%d0%bf%d1%83%d1%81%d0%ba%d0%b8-%d0%a2%d0%b5%d0%bb%d0%b5%d0%b3%d1%80%d0%b0%d0%bc-%d0%b1%d0%be%d1%82%d0%b0-%d0%be%d1%88%d0%b8%d0%b1%d0%ba%d0%b0-erroraiogram-dispatcher-dispatchercause-exc
Here you can see the code and failure.
I used :
Anaconda (version 1.7.2)
Python (version 3.8.5)
Spyder (version 4.2)
In my case as i understood the problem was not code but in the Spyder
(version 4.2)
The solution was to switch to Visual studio.
Perhaps it was not what you were looking for.


ср, 17 февр. 2021 г. в 20:41, Богдан Шкёпу <ches993@gmail.com>:

**Comment by evgfilim1** [comment] 2021-02-17 18:55
> https://ru.stackoverflow.com/questions/1241208/%d0%9f%d1%80%d0%b8-%d0%b7%d0%b0%d0%bf%d1%83%d1%81%d0%ba%d0%b8-%d0%a2%d0%b5%d0%bb%d0%b5%d0%b3%d1%80%d0%b0%d0%bc-%d0%b1%d0%be%d1%82%d0%b0-%d0%be%d1%88%d0%b8%d0%b1%d0%ba%d0%b0-erroraiogram-dispatcher-dispatchercause-exc
> Here you can see the code and failure.

@ches993 Logs in the link you provided are not the same as for the author. Your error is directly related to #496.

**Comment by morning728** [comment] 2021-08-05 14:32
I solved this problem with rebooting my PC. I guess problem appears because the processes we cant see and rebooting just stops them down
